version: '3.8'

services:
  app:
    build: .
    ports:
      - "8085:8085"
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/isms_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: isms-user
      SPRING_DATASOURCE_PASSWORD: 5trathmorE1!
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: isms_db
      MYSQL_USER: isms-user
      MYSQL_PASSWORD: 5trathmorE1!
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
