spring:
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  devtools:
    restart:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/isms_db
    username: isms-user
    password: pa******d
    driver-class-name: com.mysql.cj.jdbc.Driver

  main:
    allow-circular-references: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: wambuimuchiri036@gmail.com
    password: "zlil pqmk brfy lbcb"   
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

github:
  webhook:
    secret: my-webhook-secret

server:
  port: 8085

mpesa:
